# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('武汉', '武汉'), ('成都', '成都')], default='上海', max_length=10, verbose_name='常居地'),
        ),
    ]
