# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200812_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, verbose_name='个人形象'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1990-01-01', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '沈阳')], default='北京', max_length=20, verbose_name='常居地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='昵称'),
        ),
    ]
